#pragma once

#define  HOSTAGENT_GETHOSTADDR_RESP 10
#define  HOSTAGENT_GETHOSTADDR_REQ  11
#define  MEETINGHOST_REGISTER		12
#define  MEETINGHOST_EXIT			14
#define  MEETINGHOST_UNREGISTER		13
#define  MEETINGHOST_INVITE			16
#define  MEETINGHOSTAGNET_UI_CMD	15
#define  MEETINGHOSTAGENT_STOP      17
#define  MEETINGHOST_UI_TRANSDATA	18

//ManageSeesion¥¶¿Ì√¸¡Ó
#define  MEETINGMANAGE_SEESION_RECREATE      401
#define  MEETINGMANAGE_SEESION_REGISTERCMD   402
#define  MEETINGMANAGE_SEESION_RECVCMD_PROC  403 
#define  MEETINGMANAGE_SEESION_RESETUDP      404
#define  MEETINGMANAGE_SEESION_RESETTCP      405


#define  MEETINGMANAGE_SEESION_RESETUDP_TIMER      1
#define  MEETINGMANAGE_SEESION_RESETTCP_TIMER      2

